export enum Action {
	// User Table
	CREATE_USER = 1,
	READ_USER = 2,
	UPDATE_USER = 3,
	DELETE_USER = 4,

	// Category Table
	CREATE_CATEGORY = 5,
	READ_CATEGORY = 6,
	UPDATE_CATEGORY = 7,
	DELETE_CATEGORY = 8,

	// Conversation Table
	CREATE_CONVERSATION = 9,
	READ_CONVERSATION = 10,
	UPDATE_CONVERSATION = 11,
	DELETE_CONVERSATION = 12,

	// Message Table
	CREATE_MESSAGE = 13,
	READ_MESSAGE = 14,
	UPDATE_MESSAGE = 15,
	DELETE_MESSAGE = 16,

	// Role Table
	CREATE_ROLE = 17,
	READ_ROLE = 18,
	UPDATE_ROLE = 19,
	DELETE_ROLE = 20,

	// Service Table
	CREATE_SERVICE = 21,
	READ_SERVICE = 22,
	UPDATE_SERVICE = 23,
	DELETE_SERVICE = 24,

	// Subcategory Table
	CREATE_SUBCATEGORY = 25,
	READ_SUBCATEGORY = 26,
	UPDATE_SUBCATEGORY = 27,
	DELETE_SUBCATEGORY = 28,

	// Extra Service Table
	CREATE_EXTRA_SERVICE = 29,
	READ_EXTRA_SERVICE = 30,
	UPDATE_EXTRA_SERVICE = 31,
	DELETE_EXTRA_SERVICE = 32,

	// Cart Table
	CREATE_CART = 33,
	READ_CART = 34,
	UPDATE_CART = 35,
	DELETE_CART = 36,

	// Order Table
	CREATE_ORDER = 37,
	READ_ORDER = 38,
	UPDATE_ORDER = 39,
	DELETE_ORDER = 40
}
